name: Continuous Release
on:
  push:
jobs:
  create-zip:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'no-zip')"
    steps:
      - uses: actions/checkout@v1
      - run: mkdir zip
      - run: for i in */; do zip -r ./zip/${i%/}.$(date +'%d-%m-%Y').${{ github.run_number }}.zip "$i" *.pdf; done
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./zip/*"
          allowUpdates: true
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
